spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 2000
            read-timeout: 3000
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors:
#              - com.atguigu.order.interceptor.XTokenRequestInterceptor
feign:
  sentinel:
    enabled: true
#            retryer: feign.retryer.Default